pipeline:
  publish:
    image: plugins/docker
    registry: asia.gcr.io
    repo: asia.gcr.io/labs-127/confession
    username: _json_key
    password: ${GCP_SA_KEY}
    email: imran.ismail@icommerce.asia
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}
    build_args:
    - FB_PAGE_ACCESS_TOKEN=${FB_PAGE_ACCESS_TOKEN}
    - FB_VERIFICATION_TOKEN=${FB_VERIFICATION_TOKEN}
    - SECRET_KEY_BASE=${SECRET_KEY_BASE}
  deploy:
    image: ipedrazas/drone-helm
    api_server: https://${KUBERNETES_MASTER}/
    skip_tls_verify: true
    chart: ./charts/confession
    values: image.tag=${DRONE_COMMIT_SHA:0:7}
    release: confession
    token: ${KUBERNETES_SA_TOKEN}
